"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

if os.name == 'nt':
    VENV_BASE = os.environ['VIRTUAL_ENV']
    os.environ['PATH'] = os.path.join(VENV_BASE, 'Lib\\\\site-packages\\\\osgeo') + ';' + os.environ['PATH']
    os.environ['PROJ_LIB'] = os.path.join(VENV_BASE, 'Lib\\\\site-packages\\\\osgeo\\\\data\\\\proj') + ';' + os.environ['PATH']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fzcgqia_kn-%pc=23ufaqis=#jyfbkkq=$om^h5behqtl#fwc2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'www.geospatialib.com',
    'geospatialib.com',
]


SITE_ID = 1
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online'
        },
    }
}

AUTHENTICATION_BACKENDS = (
    'apps.main.backends.CustomAuthenticationBackend',
)

AUTH_USER_MODEL = 'main.User'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # social auth
    'django.contrib.sites',

    # postgres
    'django.contrib.postgres', # pip install psycopg2
    
    # gis
    'django.contrib.gis', 

    # local apps
    'utils',
    'htmx.hx_main',
    'htmx.hx_library',
    'apps.main',
    'apps.library',

    # 3rd-party apps
    'widget_tweaks',
    'leaflet',
    'django_htmx',
    'debug_toolbar',
    'corsheaders',
]

LEAFLET_CONFIG = {
    # 'SPATIAL_EXTENT': (5.0, 44.0, 7.5, 46),
    
    'DEFAULT_CENTER': (45, 0),
    'DEFAULT_ZOOM': 2,
    'MIN_ZOOM': 1,
    'MAX_ZOOM': 20,
    'DEFAULT_PRECISION': 6,
    
    'TILES': [],
    # 'OVERLAYS': [('Cadastral', 'http://server/a/{z}/{x}/{y}.png', {'attribution': '&copy; IGN'})],
    # 'ATTRIBUTION_PREFIX': 'Powered by django-leaflet',
    

    'SCALE': None,
    # 'MINIMAP': True,
    'RESET_VIEW': True,

    'NO_GLOBALS': False,
    'FORCE_IMAGE_PATH': True,

    'PLUGINS': {
        'geocoder': {
            'css': [
                'https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css', 
            ],
            'js': [
                'https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js',
            ],
            'auto_include': True,
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 3rd party
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'corsheaders.middleware.CorsMiddleware',

    # local
    'htmx.hx_main.middleware.HTMXDomainRestriction',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/home/tamsynmalabanan/geospatialib/project/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'apps.library.context_processors.forms',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "geospatialib",
        "USER": "super",
        "PASSWORD": "XQ3jhTme$gy8C&",
        "HOST": "tamsynmalabanan-4261.postgres.pythonanywhere-services.com",
        "PORT": "14261",
    }
}

"""
DROP DATABASE geospatialib;
CREATE DATABASE geospatialib;
\c geospatialib
CREATE EXTENSION postgis;
\dx
"""
# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = '/home/tamsynmalabanan/geospatialib/project/media'
MEDIA_URL = '/media/'
STATIC_ROOT = '/home/tamsynmalabanan/geospatialib/project/static'
STATIC_URL = '/static/'

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# for debug toolbar
INTERNAL_IPS = [
    '127.0.0.1'
]

# for captcha
RECAPTCHA_PUBLIC_KEY = '6LcNimkqAAAAAKstLLJ6qiuIpuHMiwusF7oh9ylF'
RECAPTCHA_PRIVATE_KEY = '6LcNimkqAAAAALA06RHsr8Gd3u4v55YWlXA5G_eN'

# for cors header
CORS_ALLOWED_ORIGINS = []