# Generated by Django 5.1.6 on 2025-06-24 06:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=256)),
                ('auth_srid', models.IntegerField()),
                ('srtext', models.TextField()),
                ('proj4text', models.TextField()),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField(max_length=512, unique=True, verbose_name='Path')),
            ],
            options={
                'verbose_name_plural': 'URLs',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('geojson', 'GeoJSON'), ('csv', 'CSV'), ('file', 'File'), ('xyz', 'XYZ Tiles'), ('ogc-wfs', 'OGC Web Feature Service'), ('ogc-wms', 'OGC Web Map Service')], max_length=16, verbose_name='Format')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Count')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.url', verbose_name='URL')),
            ],
            options={
                'unique_together': {('url', 'format')},
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Title')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='Type')),
                ('xField', models.CharField(blank=True, max_length=32, null=True, verbose_name='X Field')),
                ('yField', models.CharField(blank=True, max_length=32, null=True, verbose_name='Y Field')),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Bounding Box')),
                ('keywords', models.JSONField(default=list, verbose_name='Keywords')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('attribution', models.TextField(blank=True, null=True, verbose_name='Attribution')),
                ('fees', models.TextField(blank=True, null=True, verbose_name='Fees')),
                ('styles', models.JSONField(default=dict, verbose_name='Styles')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='main.collection', verbose_name='Collection')),
                ('srid', models.ForeignKey(default=4326, on_delete=django.db.models.deletion.PROTECT, to='main.spatialrefsys', verbose_name='SRID')),
            ],
            options={
                'unique_together': {('collection', 'name')},
            },
        ),
    ]
